//аунтефикация*
//восстановление пароля
export const FORGOT_PASSWORD_SET_VALUE: "FORGOT_PASSWORD_FORM_SET_VALUE" = "FORGOT_PASSWORD_FORM_SET_VALUE";
export const FORGOT_PASSWORD_SUBMIT: "FORGOT_PASSWORD_FORM_SUBMIT" = "FORGOT_PASSWORD_FORM_SUBMIT";
export const FORGOT_PASSWORD_SUBMIT_SUCCESS: "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS" =
  "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS";
export const FORGOT_PASSWORD_SUBMIT_FAILED: "FORGOT_PASSWORD_FORM_SUBMIT_FAILED" =
  "FORGOT_PASSWORD_FORM_SUBMIT_FAILED";

//сброс пароля
export const RESET_PASSWORD_SET_VALUE: "RESET_PASSWORD_SET_VALUE" = "RESET_PASSWORD_SET_VALUE";
export const RESET_PASSWORD_SUBMIT: "RESET_PASSWORD_SUBMIT" = "RESET_PASSWORD_SUBMIT";
export const RESET_PASSWORD_SUBMIT_SUCCESS: "RESET_PASSWORD_SUBMIT_SUCCESS"  = "RESET_PASSWORD_SUBMIT_SUCCESS";
export const RESET_PASSWORD_SUBMIT_FAILED: "RESET_PASSWORD_SUBMIT_FAILED" = "RESET_PASSWORD_SUBMIT_FAILED";

//регистрация
export const REGISTER_SET_VALUE: "REGISTER_SET_VALUE" = "REGISTER_SET_VALUE";
export const REGISTER_SUBMIT: "REGISTER_SUBMIT" = "REGISTER_SUBMIT";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";

//авторизация
export const LOGIN_SET_VALUE: "LOGIN_SET_VALUE" = "LOGIN_SET_VALUE";
export const LOGIN_SUBMIT: "LOGIN_SUBMIT" = "LOGIN_SUBMIT";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILED: "LOGIN_FAILED" = "LOGIN_FAILED";

//проверка авторизации
export const GET_ACCESS_SUCCESS: "GET_ACCESS_SUCCESS" = "GET_ACCESS_SUCCESS";
export const GET_ACCESS_FAILED: "GET_ACCESS_FAILED"  = "GET_ACCESS_FAILED";
export const GET_ACCESS_LOADED: "GET_ACCESS_LOADED" = "GET_ACCESS_LOADED";

//изменение данных пользователя
export const UPDATE_INFO_SUBMIT: "UPDATE_INFO_SUBMIT" = "UPDATE_INFO_SUBMIT";
export const UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS" = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAILED: "UPDATE_INFO_FAILED" = "UPDATE_INFO_FAILED";

// выход из акаунта
export const LOGOUT_SUBMIT: "LOGOUT_SUBMIT" = "LOGOUT_SUBMIT";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED: "LOGOUT_FAILED" = "LOGOUT_FAILED";



//конструктор*
export const ADD_ITEM: "ADD_ITEM" = "ADD_ITEM";
export const DELETE_ITEM: "DELETE_ITEM" = "DELETE_ITEM";
export const SORT_ITEM: "SORT_ITEM" = "SORT_ITEM";
export const RESET_INGREDIENT: "RESET_INGREDIENT" = "RESET_INGREDIENT";


//ингредиенты*
export const GET_ITEMS_REQUEST:"GET_ITEM_REQUEST"  = "GET_ITEM_REQUEST";
export const GET_ITEMS_SUCCESS: "GET_ITEM_SUCCESS"= "GET_ITEM_SUCCESS";
export const GET_ITEMS_ERROR: "GET_ITEM_ERROR" = "GET_ITEM_ERROR";
export const INCREMENT_COUNT: "INCREASE_COUNT"= "INCREASE_COUNT";
export const DECREMENT_COUNT: "DECREASE_COUNT" = "DECREASE_COUNT";
export const SET_COUNT: "SET_COUNT" = "SET_COUNT";


//модалка с ингредиентом*
export const OPEN_INGREDIENT_MODAL: "OPEN_INGREDIENT_MODAL" = "OPEN_INGREDIENT_MODAL";
export const CLOSE_INGREDIENT_MODAL: "CLOSE_INGREDIENT_MODAL" = "CLOSE_INGREDIENT_MODAL";



//модалка с номером заказа*
export const GET_ORDER_DATA_REQUEST: "GET_ORDER_DATA_REQUEST" = "GET_ORDER_DATA_REQUEST";
export const GET_ORDER_DATA_SUCCESS: "GET_ORDER_DATA_SUCCESS" = "GET_ORDER_DATA_SUCCESS";
export const GET_ORDER_DATA_ERROR: "GET_ORDER_DATA_ERROR" = "GET_ORDER_DATA_ERROR";
export const CLOSE_ORDER_MODAL: "CLOSE_ORDER_MODAL" = "CLOSE_ORDER_MODAL";
export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";
export const ORDER_ERROR: "ORDER_ERROR"= "ORDER_ERROR";
export const RESET_ORDER: "RESET_ORDER" = "RESET_ORDER";



//модалка с заказом*
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR: "GET_ORDER_ERROR" = "GET_ORDER_ERROR";


//вебсокет*
export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" = "WS_CONNECTION_CLOSED";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";


//вебсокет профиля*
export const WS_CONNECTION_START_PROFILE: "WS_CONNECTION_START_PROFILE" = "WS_CONNECTION_START_PROFILE";
export const WS_CONNECTION_SUCCESS_PROFILE: "WS_CONNECTION_SUCCESS_PROFILE" = "WS_CONNECTION_SUCCESS_PROFILE";
export const WS_CONNECTION_ERROR_PROFILE: "WS_CONNECTION_ERROR_PROFILE" = "WS_CONNECTION_ERROR_PROFILE";
export const WS_CONNECTION_CLOSE_PROFILE: "WS_CONNECTION_CLOSE_PROFILE" = "WS_CONNECTION_CLOSE_PROFILE";
export const WS_CONNECTION_CLOSED_PROFILE: "WS_CONNECTION_CLOSED_PROFILE" = "WS_CONNECTION_CLOSED_PROFILE";
export const WS_GET_MESSAGE_PROFILE: "WS_GET_MESSAGE_PROFULE" = "WS_GET_MESSAGE_PROFULE";